name: Run Command In Archlinux Docker Container
description: Run Command In Archlinux Docker Container
inputs:
  dir:
    description: Directory to run from
    required: false
    default: '.'
  run:
    description: Script to run
    required: true
  github_token:
    description: Token for repo access
    required: true
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.run }}
