name: Reset submodules

on: push

permissions:
  packages: write
  contents: write


jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - run: git submodule deinit ${{ github.workspace }}/python
      - run: git submodule deinit ${{ github.workspace }}/kloak
