name: Reset submodules

on: push

permissions:
  packages: write
  contents: write


jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          cd ${{ github.workspace }} && 
          git config --add submodule.python.active false || 
          git config --unset submodule.python.active 

